name: Generate Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tw√≥j profil
        uses: actions/checkout@v3

      - name: Checkout skryptu statystyk
        uses: actions/checkout@v3
        with:
          repository: kitajusSus/github-stats
          path: stats-tool # Pobiera skrypt do osobnego folderu

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r stats-tool/requirements.txt

      - name: Generate Stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Uruchomienie skryptu z odpowiednimi argumentami
          python stats-tool/main.py --user TWOJ_LOGIN --token $GH_TOKEN --output generated

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/
          git commit -m "Update GitHub stats" || exit 0
          git push
